/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "stm32f411xe.h"
#include "fpu.h"
#include "uart.h"
#include "timebase.h"

#define GPIOAEN				(1U << 0)
#define PIN5				(1U << 5)
#define LED_PIN				PIN5

int main(void)
{

	/*Enable FPU*/
	fpu_enable();

	/*Initialize debug UART*/
	debug_uart_init();

	/*Initialize timebase*/
	timebase_init();

    /* Loop forever */
	while(1){

		printf("Hello from STM32\r\n");

		delay(1);
	}
}
